version: '3.7'
networks: 
  backend:
    driver: bridge

services: 
  nestjs:
    build: 
      context: .
      dockerfile: docker/nestjs/Dockerfile
    container_name: prj_nestjs
    restart: always
    volumes: 
      - ./:/var/www/nestjs
    networks: 
      - backend
  
  nginx:
    container_name: prj_nginx
    image: nginx:1.16.1-alpine
    restart: always
    volumes: 
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    - ./docker/log/nginx:/var/log/nginx
    ports: 
      - '80:80'
      - '443:443'
    networks: 
    - backend

  mysql:
    container_name: prj_mysql
    image: mysql:5.7.22
    restart: always
    command: 
      --max_allowed_packet=32505856  
      --wait_timeout=28800 
      --sql-mode=ALLOW_INVALID_DATES,ANSI_QUOTES,ERROR_FOR_DIVISION_BY_ZERO,HIGH_NOT_PRECEDENCE,IGNORE_SPACE,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_BACKSLASH_ESCAPES,NO_DIR_IN_CREATE,NO_ENGINE_SUBSTITUTION,NO_FIELD_OPTIONS,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_UNSIGNED_SUBTRACTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,PIPES_AS_CONCAT,REAL_AS_FLOAT,STRICT_ALL_TABLES,STRICT_TRANS_TABLES,ANSI,DB2,MAXDB,MSSQL,MYSQL323,MYSQL40,ORACLE,POSTGRESQL,TRADITIONAL
    environment: 
      - MYSQL_ROOT_PASSWORD=abcdef123
      - MYSQL_DATABASE=nestjs
      - MYSQL_USER=dudy206
      - MYSQL_PASSWORD=abcdef123
    networks: 
      - backend
    
  phpmyadmin:
    container_name: prj_phpmyadmin
    image: phpmyadmin:5.1.0
    environment: 
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=abcdef123
      - UPLOAD_LIMIT=20000000
    ports: 
      - '8181:80'
    networks: 
      - backend
    depends_on: 
      - mysql
